server:
  port: 8003
spring:
  application:
    name: web-chat
  rabbitmq:
    host: 192.168.226.180
    username: admin
    password: admin
    virtual-host: /admin
    port: 5672
  redis:
    host: 192.168.226.180

eureka:
  client:
    service-url:
      defaultZone: http://localhost:10000/eureka

zk:
  host: 192.168.226.180:2181
