server:
  port: 8000

spring:
  application:
    name: web-user
  datasource:
    url: jdbc:mysql://localhost:3306/txbb
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver

eureka:
  client:
    service-url:
      defaultZone: http://localhost:10000/eureka
