server:
  port: 8001

spring:
  application:
    name: resource-server
  servlet:
    multipart:
      max-file-size: 10MB

eureka:
  client:
    service-url:
      defaultZone: http://localhost:10000/eureka

fdfs:
  pool:
    jmx-enabled: false
  tracker-list:
    - 192.168.226.180:22122
  thumb-image:
    width: 80
    height: 80
  serverip:
    192.168.226.180